### PR TITLE
final fixes for release

### LINKED ISSUE #117: final fixes for release

### PR DESCRIPTION
**Pull request by Valmetti**
resolves #117 

- removed pie chart from distributions,
- added legend to distributions,
- text changes,
- bumbed version

### CODE REVIEW

File: src/components/screens/portfolio/distributions-screen.tsx [hunk 1]
```diff
@@ -221,13 +137,42 @@ const DistributionsScreen: React.FC = () => {
...
+  );
+
+  /**
+   * Renders legends
+   */
+  const renderLegends = () => (
+    <Card style={[ styles.distributionCard, { marginTop: theme.spacing(2) } ]}>
+      { renderlegend("rgb(200, 40, 40)", "Osakerahastot") }
+      { renderlegend("rgb(230, 130, 40)", "Yhdistelmärahastot") }
+      { renderlegend("rgb(80, 140, 80)", "korkorahastot") }
```
Comment (jarinykanen) [inline src/components/screens/portfolio/distributions-screen.tsx:175]: Add localization

**Review by jarinykanen — APPROVED** [review]
