### PR TITLE
Feature 91 fixes to version 3

### LINKED ISSUE #91: fixes to version 3
Fixes to bugs and comments presented by the customer.

### PR DESCRIPTION
**Pull request by Valmetti**
resolves #91

### CODE REVIEW

File: src/components/screens/funds/subscription-settings-screen.tsx [hunk 1]
```diff
@@ -582,29 +594,22 @@ const SubscriptionSettingsScreen: React.FC = () => {
...
-      <BackButton/>
-      <KeyboardAvoidingView behavior={ Platform.OS === "ios" ? "padding" : "height" }>
-        <ScrollView>
-          { renderContent() }
-        </ScrollView>
-      </KeyboardAvoidingView>
+      <KeyboardAwareScrollView>
+        { Platform.OS === "ios" &&
+          <BackButton/>
+        }
```
Comment (jarinykanen) [inline src/components/screens/funds/subscription-settings-screen.tsx:605]:
```suggestion
        { Platform.OS === "ios" && <BackButton/> }
```

File: src/components/screens/portfolio/transaction-details-screen.tsx [hunk 2]
```diff
@@ -60,7 +62,20 @@ const TransactionDetailsScreen: React.FC = () => {
...
+     * Total value by transaction type
+     */
+    const totalValueByTransactionType = () => {
+      if (transactionType === "SUBSCRIPTION") {
+        return new BigNumber(Number(totalValue) - Number(provision));
+      }
+      if (transactionType === "REDEMPTION") {
+        return new BigNumber(Number(totalValue) + Number(provision));
+      }
+      return new BigNumber(totalValue);
```
Comment (jarinykanen) [inline src/components/screens/portfolio/transaction-details-screen.tsx:77]:
```suggestion
      }

      if (transactionType === "REDEMPTION") {
        return new BigNumber(Number(totalValue) + Number(provision));
      }

      return new BigNumber(totalValue);
```

File: src/utils/funds.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+    const nameA = a.longName.fi;
+    const nameB = b.longName.fi;
+    return nameA.localeCompare(nameB);
+  };
+
+  /**
+   * Returns true if given fund is Seligson fund
+   */
+  export const isSeligsonFund = ({ longName }: Fund): boolean =>
+    GenericUtils.getLocalizedValue(longName).includes("Seligson");
```
Comment (jarinykanen) [inline src/utils/funds.ts:25]:
```suggestion
  export const isSeligsonFund = ({ longName }: Fund): boolean => GenericUtils.getLocalizedValue(longName).includes("Seligson");
```

**Review by jarinykanen — APPROVED** [review]
