### PR TITLE
Feature 109 fixes to version 5

### LINKED ISSUE #109: fixes to version 5

### PR DESCRIPTION
**Pull request by Valmetti**
resolves #109

### CODE REVIEW

File: src/components/generic/fund-card.tsx [hunk 1]
```diff
@@ -75,6 +76,21 @@ const FundCard: React.FC<Props> = ({ fund }) => {
...
+    if (seligsonFund || ltFund) {
+      return (
+        <View style={ styles.fundLogoContainer }>
+          { seligsonFund && <SeligsonLogoSmall/> }
+          { ltFund && <LahitapiolaLogoSmall/> }
+        </View>
+      );
+    }
+    return null;
+  };
```
Comment (jarinykanen) [inline src/components/generic/fund-card.tsx:92]: Make this if check the other way around (if (!seligsonFund && !ltFund))

File: src/components/generic/fund-card.tsx [hunk 2]
```diff
@@ -85,11 +101,10 @@ const FundCard: React.FC<Props> = ({ fund }) => {
         <View style={ styles.cardRow }>
           <View style={ styles.cardColumn }>
             <View style={ styles.fundName }>
-              <View style={ styles.fundLogoContainer }>
-                { SeligsonFund ? <SeligsonLogoSmall/> : <LahitapiolaLogoSmall/> }
-              </View>
+              { logoContainer() }
               <Text style={[ theme.fonts.medium, { flex: 1 } ]}>
                 { GenericUtils.getLocalizedValue(shortName) }
+                { fund.shortName.fi.includes("Russia") && "(Suljettu, osuuden arvo perustuu rahaston viimeisempää 25.02.2022 laskettuun arvoon. Nykyinen arvo ei ole tiedossa"}
```
Comment (jarinykanen) [inline src/components/generic/fund-card.tsx:107]: Does this need localization?

File: src/components/generic/fund-details.tsx [hunk 3]
```diff
@@ -25,12 +26,33 @@ interface Props {
...
+
+  /**
+   * Returns whether buy button should be disabled or not
+   * 
+   * @returns whether buy button should be disabled or not
+   */
+  const isBuyDisabled = () => {
+    const { subscriptionBankAccounts } = fund;
+    return !subscriptionBankAccounts?.length;
+  };
```
Comment (jarinykanen) [inline src/components/generic/fund-details.tsx:54]:
```suggestion
  const isBuyDisabled = () => !fund.subscriptionBankAccounts?.length;
```

File: src/components/generic/fund-details.tsx [hunk 4]
```diff
@@ -71,6 +95,52 @@ const FundDetails: React.FC<Props> = ({ fund, onSubscribePress }) => {
     </>
   );
 
+  /**
+   * Renders share values
+   *
+   * @param currency currency value
+   * @returns
```
Comment (jarinykanen) [inline src/components/generic/fund-details.tsx:102]:
```suggestion
```

File: src/components/generic/portfolio-security-card.tsx [hunk 5]
```diff
@@ -64,15 +67,28 @@ const PortfolioSecurityCard: React.FC<Props> = ({ portfolioSecurity, fund }) =>
     );
   };
 
+  /**
+   * Renders logo container if fund is either Seligson fund or LähiTapiola fund
+   */
+  const logoContainer = () => {
+    if (seligsonFund || ltFund) {
```
Comment (jarinykanen) [inline src/components/generic/portfolio-security-card.tsx:74]: Check previous comments

File: src/utils/funds.ts [hunk 6]
```diff
@@ -49,6 +55,34 @@ namespace FundUtils {
     ...getLtFunds(funds).sort(FundUtils.SortFundsByName)
   ];
 
+  /**
+   * Resolves "main" security for the fund
+   * 
+   * @param fundId fund id
+   * @returns main security or null if not found
+   */
+  export const resolveMainSecurity = async (securitiesContext: SecuritiesApiContextType, fundId: string) => {
```
Comment (jarinykanen) [inline src/utils/funds.ts:64]:
```suggestion
  /**
   * Resolves "main" security for the fund
   *
   * @param securitiesContext securities context
   * @param fundId fund id
   * @returns main security or null if not found
   */
  export const resolveMainSecurity = async (securitiesContext: SecuritiesApiContextType, fundId: string) => {
```

File: src/utils/injectables.ts [hunk 7]
```diff
@@ -126,7 +127,7 @@ namespace Injectables {
               ticks: {
                 precision: 0,
                 callback: function(value, index, values) {
-                  return new Intl.NumberFormat("fi-FI", { style: "currency", currency: "${valueCurrency}" }).format(value).replace(",00", "")
+                  return parseFloat(value).toFixed() + " ${strings.currency.symbol[valueCurrency as Currency]}";
```
Comment (jarinykanen) [inline src/utils/injectables.ts:130]: Use string literal syntax

**Review by jarinykanen — CHANGES_REQUESTED** [review]
