### PR TITLE
Feature 135 company portfolio fix

### LINKED ISSUE #135: company portfolio fix

### PR DESCRIPTION
**Pull request by Chi-Chu319**
resolves #135

### CODE REVIEW

File: src/styles/screens/portfolio/company-select.ts [hunk 1]
```diff
@@ -18,6 +18,6 @@ export default StyleSheet.create({
     color: "white",
     paddingLeft: 10,
     fontSize: 14
-  }
+  },
```
Comment (jarinykanen) [inline src/styles/screens/portfolio/company-select.ts:21]:
```suggestion
  }
```

**Review by jarinykanen — APPROVED** [review]
