### PR TITLE
Feature 72 inconstant styling fixes

### LINKED ISSUE #72: inconstant styling fixes

### PR DESCRIPTION
**Pull request by Valmetti**
resolves #72

### CODE REVIEW

File: src/components/generic/chart-range-selector.tsx [hunk 1]
```diff
@@ -135,25 +136,36 @@ const ChartRangeSelector: React.FC<Props> = ({ selectedRange, loading, onDateRan
...
-      <View style={{ flexDirection: "row", justifyContent: "space-evenly" }}>
+      <View style={ styles.dateRangeButtonRow }>
         { renderDatePicker() }
-        <Button onPress={ onCloseDateSelection }>
-          { strings.generic.cancel }
-        </Button>
-        <Button onPress={ onConfirmDates }>
-          { strings.generic.ok }
-        </Button>
+        <View style={{ flexDirection: "row", flex: 1, alignItems: "center", justifyContent: "flex-end" }}>
```
Comment (lauriLukkarinen) [inline src/components/generic/chart-range-selector.tsx:153]: Move styles to style file

File: src/components/screens/funds/subscription-settings-screen.tsx [hunk 2]
```diff
@@ -487,7 +495,23 @@ const SubscriptionSettingsScreen: React.FC = () => {
...
           () => (
-            <Text>
+            <Text style={ theme.fonts.medium }>
+              { strings.subscription.subscriptionAmount }
+            </Text>
+          ),
+          renderSumInput
+        )
+      }
+      <View style={ !validNumber(subscriptionSettings.sum) && subscriptionSettings.sum.length ? styles.validSum : styles.invalidSum }>
```
Comment (lauriLukkarinen) [inline src/components/screens/funds/subscription-settings-screen.tsx:505]:
```suggestion
      <View
        style={
          !validNumber(subscriptionSettings.sum) && subscriptionSettings.sum.length ?
            styles.validSum :
            styles.invalidSum
        }
      >
```

File: src/localization/strings.ts [hunk 3]
```diff
@@ -167,7 +167,13 @@ export interface Strings extends LocalizedStringsMethods {
...
         description: string;
       };
-    }
+    },
+    nonSubscribableFund: {
+      description: string,
+      guideLink: string,
+      videoBlog: string,
+      videoBlogLink: string
+    };
```
Comment (lauriLukkarinen) [inline src/localization/strings.ts:176]:
```suggestion
    };
    nonSubscribableFund: {
      description: string;
      guideLink: string;
      videoBlog: string;
      videoBlogLink: string;
    };
```
